baseURL = "https://quartz.jzhao.xyz/"
languageCode = "en-us"
googleAnalytics = "G-XYFD95KB4J"
relativeURLs = false
disablePathToLower = true
ignoreFiles = [
    "/content/templates/*",
    "/content/private/*",
]
summaryLength = 20
paginate = 10
sectionPagesMenu = "main"
pluralizeListTitles = false

enableGitInfo = true

[markup]
    defaultMarkdownHandler = 'goldmark'
    [markup.tableOfContents]
        endLevel = 3
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        anchorLineNos = false
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        style = "dracula"
    [frontmatter]
        lastmod = ["lastmod", ":git", ":fileModTime", "date", "publishDate"]
        publishDate = ["publishDate", "date"]
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            linkifyProtocol = 'https'
            strikethrough = true
            table = true
            taskList = true
            typographer = true
            [markup.goldmark.parser]
            autoHeadingID = true
            autoHeadingIDType = 'github'
        [markup.goldmark.parser.attribute]
            block = false
            title = true
        [markup.goldmark.renderer]
            hardWraps = true
            unsafe = false
            xhtml = false
    [markup.asciidocExt]
        backend = 'html5'
        extensions = []
        failureLevel = 'fatal'
        noHeaderOrFooter = true
        preserveTOC = false
        safeMode = 'unsafe'
        sectionNumbers = false
        trace = false
        verbose = false
        workingFolderCurrent = false
        [markup.asciidocExt.attributes]
    [params.page.math]
        enable = true
        mhchem = true
        copyTex = true
[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
