name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo
    paths-ignore:
      - 'content/private/**'
      - 'content/templates/**'
      - 'content/.obsidian/**'
      - 'content/.obsidian.vimrc'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # TODO: Fix this 
      # - name: Build Link Index
      #   uses: jackyzha0/hugo-obsidian@v2.17
      #   with:
      #     index: true
      #     input: content
      #     output: assets/indices
      #     root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      
      # Fix for https://github.com/gohugoio/hugo/issues/9810
      - name: Git config
        run: git config --global core.quotepath false

      - name: Build
        run: hugo --minify --cleanDestinationDir --gc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
          cname: plundration.github.io/
  